// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
		seed: 'tsx prisma/seed.ts'
	},
	datasource: {
		// Migrations run against the direct (non-pooled) Neon endpoint; the pooled
		// URL is reserved for the app runtime via $app/env/private.
		url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL']
	}
});
